import { TenantModel, TenantType, ITenant } from '../models/tenant.model';
import {
    CITIZEN_TENANT_ID,
    CITIZEN_TENANT_NAME,
    PLATFORM_TENANT_ID,
    PLATFORM_TENANT_NAME,
} from '../../../shared/constants/tenant.constants';

export class TenantService {
    /**
     * Get tenant by ID
     */
    static async getTenantById(tenantId: string): Promise<ITenant | null> {
        return TenantModel.findOne({ tenantId });
    }

    /**
     * Update tenant details
     */
    static async updateTenant(
        tenantId: string,
        updates: Partial<Omit<ITenant, 'tenantId' | 'type'>>
    ): Promise<ITenant | null> {
        return TenantModel.findOneAndUpdate(
            { tenantId },
            { $set: updates },
            { new: true }
        );
    }

    /**
     * Get all active tenants (for super admin use)
     */
    static async getAllTenants(): Promise<ITenant[]> {
        return TenantModel.find({ isActive: true });
    }

    /**
     * Create a new tenant. The tenantId should be a UUID-based string
     * (e.g. `TENANT-${uuidv4()}`) generated by the caller.
     */
    static async createTenant(data: {
        tenantId: string;
        name: string;
        type: string;
        logo?: string;
        contactEmail?: string;
        contactPhone?: string;
        address?: string;
    }): Promise<ITenant> {
        const tenant = new TenantModel(data);
        await tenant.save();
        return tenant;
    }

    /**
     * Check if tenant exists
     */
    static async tenantExists(tenantId: string): Promise<boolean> {
        const count = await TenantModel.countDocuments({ tenantId });
        return count > 0;
    }

    /**
     * Get or create the shared Citizen tenant (used by all PASSENGER users).
     * Uses a stable UUID-based ID defined in tenant.constants.ts.
     */
    static async getOrCreateCitizenTenant(): Promise<ITenant> {
        let tenant = await TenantModel.findOne({ tenantId: CITIZEN_TENANT_ID });

        if (!tenant) {
            tenant = await TenantModel.create({
                tenantId: CITIZEN_TENANT_ID,
                name: CITIZEN_TENANT_NAME,
                type: TenantType.CITIZEN,
                isActive: true,
            });
            console.log(`[TenantService] Created citizen tenant: ${CITIZEN_TENANT_ID}`);
        }

        return tenant;
    }

    /**
     * Get or create the Platform tenant (used by SUPER_ADMIN users).
     * Uses a stable UUID-based ID defined in tenant.constants.ts.
     */
    static async getOrCreatePlatformTenant(): Promise<ITenant> {
        let tenant = await TenantModel.findOne({ tenantId: PLATFORM_TENANT_ID });

        if (!tenant) {
            tenant = await TenantModel.create({
                tenantId: PLATFORM_TENANT_ID,
                name: PLATFORM_TENANT_NAME,
                type: TenantType.OPERATOR,
                isActive: true,
            });
            console.log(`[TenantService] Created platform tenant: ${PLATFORM_TENANT_ID}`);
        }

        return tenant;
    }

    /**
     * @deprecated Use getOrCreateCitizenTenant() instead.
     * Kept for backward compatibility during migration.
     */
    static async getOrCreateDefaultTenant(): Promise<ITenant> {
        return this.getOrCreateCitizenTenant();
    }
}
